### ISSUE TITLE
What is the point of creating a theme based site blocker? Site blockers are meant to block the sites automatically in the backend once added as a chrome extension. Can you please explain what's the need of themes or gifs in it?

### ISSUE THREAD

**Issue by SHRIYA1706** [Pankajtanwarbanna/shark-tank-theme-site-blocker#1]
What is the point of creating a theme based site blocker? Site blockers are meant to block the sites automatically in the backend once added as a chrome extension. Can you please explain what's the need of themes or gifs in it?

**Comment by pankaj-garaaz** [comment]
Hi Shriya,

I'm glad that you tried out the tiny tool and had questions. The shark tank theme-based site blocker project was created just for fun. Once you load it in your browser, it automatically blocks the mentioned websites and shows funny shark tank memes.

Let me know if you have any other questions. Happy to answer :)

Best
Pankaj

**Comment by Pankajtanwarbanna** [comment]
Hi Shriya,

I'm glad that you tried out the tiny tool and had questions. The shark tank theme-based site blocker project was created just for fun. Once you load it in your browser, it automatically blocks the mentioned websites and shows funny shark tank memes.

Let me know if you have any other questions. Happy to answer :)

otherwise, allow me to close the issue.

Best
Pankaj

**Comment by SHRIYA1706** [comment]
Ya you can close it. Thanks.
